name: version update


on:
  push:
    branches:
      - master


jobs:
  migrate_and_push:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Get last commit message
        id: get_commit_message
        run: echo "::set-output name=message::$(git log --format=%B -n 1)"

      - name: Extract version from commit message
        id: extract_version
        run: |
          commit_message="${{ steps.get_commit_message.outputs.message }}"
          version=$(echo "$commit_message" | grep -oP '\[version: \K[^\]]+(?=\])')

          # Check if version exists
          if [ -n "$version" ]; then
            echo "Extracted version: $version"
            sed -i "s/\(version: \)[0-9.]\+/\1$version/" version.txt
            echo "---------"
            git status
            git add .
            git commit -m "version update" || true
            git push origin master || true
          else
            echo "Version not found in commit message. Skipping additional commands."
          fi